/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CvRouteImport } from './routes/cv'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as CoverLetterRouteImport } from './routes/cover-letter'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as AtsRouteImport } from './routes/ats'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItIndexRouteImport } from './routes/it/index'
import { Route as GerIndexRouteImport } from './routes/ger/index'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as EsIndexRouteImport } from './routes/es/index'
import { Route as DeIndexRouteImport } from './routes/de/index'
import { Route as PromptSlugRouteImport } from './routes/prompt.$slug'
import { Route as ItPricingRouteImport } from './routes/it/pricing'
import { Route as ItMarketplaceRouteImport } from './routes/it/marketplace'
import { Route as ItCvRouteImport } from './routes/it/cv'
import { Route as ItCreatorsRouteImport } from './routes/it/creators'
import { Route as ItCreatorRouteImport } from './routes/it/creator'
import { Route as ItCoverLetterRouteImport } from './routes/it/cover-letter'
import { Route as ItBundlesRouteImport } from './routes/it/bundles'
import { Route as ItAtsRouteImport } from './routes/it/ats'
import { Route as FrPricingRouteImport } from './routes/fr/pricing'
import { Route as FrMarketplaceRouteImport } from './routes/fr/marketplace'
import { Route as FrCvRouteImport } from './routes/fr/cv'
import { Route as FrCreatorsRouteImport } from './routes/fr/creators'
import { Route as FrCreatorRouteImport } from './routes/fr/creator'
import { Route as FrCoverLetterRouteImport } from './routes/fr/cover-letter'
import { Route as FrBundlesRouteImport } from './routes/fr/bundles'
import { Route as FrAtsRouteImport } from './routes/fr/ats'
import { Route as EsPricingRouteImport } from './routes/es/pricing'
import { Route as EsMarketplaceRouteImport } from './routes/es/marketplace'
import { Route as EsCvRouteImport } from './routes/es/cv'
import { Route as EsCreatorsRouteImport } from './routes/es/creators'
import { Route as EsCreatorRouteImport } from './routes/es/creator'
import { Route as EsCoverLetterRouteImport } from './routes/es/cover-letter'
import { Route as EsBundlesRouteImport } from './routes/es/bundles'
import { Route as EsAtsRouteImport } from './routes/es/ats'
import { Route as DePricingRouteImport } from './routes/de/pricing'
import { Route as DeMarketplaceRouteImport } from './routes/de/marketplace'
import { Route as DeCvRouteImport } from './routes/de/cv'
import { Route as DeCreatorsRouteImport } from './routes/de/creators'
import { Route as DeCreatorRouteImport } from './routes/de/creator'
import { Route as DeCoverLetterRouteImport } from './routes/de/cover-letter'
import { Route as DeBundlesRouteImport } from './routes/de/bundles'
import { Route as DeAtsRouteImport } from './routes/de/ats'
import { Route as BundleSlugRouteImport } from './routes/bundle.$slug'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ItPromptSlugRouteImport } from './routes/it/prompt.$slug'
import { Route as ItBundleSlugRouteImport } from './routes/it/bundle.$slug'
import { Route as FrPromptSlugRouteImport } from './routes/fr/prompt.$slug'
import { Route as FrBundleSlugRouteImport } from './routes/fr/bundle.$slug'
import { Route as EsPromptSlugRouteImport } from './routes/es/prompt.$slug'
import { Route as EsBundleSlugRouteImport } from './routes/es/bundle.$slug'
import { Route as DePromptSlugRouteImport } from './routes/de/prompt.$slug'
import { Route as DeBundleSlugRouteImport } from './routes/de/bundle.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterRoute = CoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsRoute = AtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItIndexRoute = ItIndexRouteImport.update({
  id: '/it/',
  path: '/it/',
  getParentRoute: () => rootRouteImport,
} as any)
const GerIndexRoute = GerIndexRouteImport.update({
  id: '/ger/',
  path: '/ger/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeIndexRoute = DeIndexRouteImport.update({
  id: '/de/',
  path: '/de/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptSlugRoute = PromptSlugRouteImport.update({
  id: '/prompt/$slug',
  path: '/prompt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ItPricingRoute = ItPricingRouteImport.update({
  id: '/it/pricing',
  path: '/it/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ItMarketplaceRoute = ItMarketplaceRouteImport.update({
  id: '/it/marketplace',
  path: '/it/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ItCvRoute = ItCvRouteImport.update({
  id: '/it/cv',
  path: '/it/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ItCreatorsRoute = ItCreatorsRouteImport.update({
  id: '/it/creators',
  path: '/it/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ItCreatorRoute = ItCreatorRouteImport.update({
  id: '/it/creator',
  path: '/it/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const ItCoverLetterRoute = ItCoverLetterRouteImport.update({
  id: '/it/cover-letter',
  path: '/it/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ItBundlesRoute = ItBundlesRouteImport.update({
  id: '/it/bundles',
  path: '/it/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const ItAtsRoute = ItAtsRouteImport.update({
  id: '/it/ats',
  path: '/it/ats',
  getParentRoute: () => rootRouteImport,
} as any)
const FrPricingRoute = FrPricingRouteImport.update({
  id: '/fr/pricing',
  path: '/fr/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FrMarketplaceRoute = FrMarketplaceRouteImport.update({
  id: '/fr/marketplace',
  path: '/fr/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const FrCvRoute = FrCvRouteImport.update({
  id: '/fr/cv',
  path: '/fr/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const FrCreatorsRoute = FrCreatorsRouteImport.update({
  id: '/fr/creators',
  path: '/fr/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const FrCreatorRoute = FrCreatorRouteImport.update({
  id: '/fr/creator',
  path: '/fr/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const FrCoverLetterRoute = FrCoverLetterRouteImport.update({
  id: '/fr/cover-letter',
  path: '/fr/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const FrBundlesRoute = FrBundlesRouteImport.update({
  id: '/fr/bundles',
  path: '/fr/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const FrAtsRoute = FrAtsRouteImport.update({
  id: '/fr/ats',
  path: '/fr/ats',
  getParentRoute: () => rootRouteImport,
} as any)
const EsPricingRoute = EsPricingRouteImport.update({
  id: '/es/pricing',
  path: '/es/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EsMarketplaceRoute = EsMarketplaceRouteImport.update({
  id: '/es/marketplace',
  path: '/es/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const EsCvRoute = EsCvRouteImport.update({
  id: '/es/cv',
  path: '/es/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const EsCreatorsRoute = EsCreatorsRouteImport.update({
  id: '/es/creators',
  path: '/es/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const EsCreatorRoute = EsCreatorRouteImport.update({
  id: '/es/creator',
  path: '/es/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const EsCoverLetterRoute = EsCoverLetterRouteImport.update({
  id: '/es/cover-letter',
  path: '/es/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const EsBundlesRoute = EsBundlesRouteImport.update({
  id: '/es/bundles',
  path: '/es/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const EsAtsRoute = EsAtsRouteImport.update({
  id: '/es/ats',
  path: '/es/ats',
  getParentRoute: () => rootRouteImport,
} as any)
const DePricingRoute = DePricingRouteImport.update({
  id: '/de/pricing',
  path: '/de/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DeMarketplaceRoute = DeMarketplaceRouteImport.update({
  id: '/de/marketplace',
  path: '/de/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const DeCvRoute = DeCvRouteImport.update({
  id: '/de/cv',
  path: '/de/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const DeCreatorsRoute = DeCreatorsRouteImport.update({
  id: '/de/creators',
  path: '/de/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const DeCreatorRoute = DeCreatorRouteImport.update({
  id: '/de/creator',
  path: '/de/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const DeCoverLetterRoute = DeCoverLetterRouteImport.update({
  id: '/de/cover-letter',
  path: '/de/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const DeBundlesRoute = DeBundlesRouteImport.update({
  id: '/de/bundles',
  path: '/de/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const DeAtsRoute = DeAtsRouteImport.update({
  id: '/de/ats',
  path: '/de/ats',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleSlugRoute = BundleSlugRouteImport.update({
  id: '/bundle/$slug',
  path: '/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ItPromptSlugRoute = ItPromptSlugRouteImport.update({
  id: '/it/prompt/$slug',
  path: '/it/prompt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ItBundleSlugRoute = ItBundleSlugRouteImport.update({
  id: '/it/bundle/$slug',
  path: '/it/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FrPromptSlugRoute = FrPromptSlugRouteImport.update({
  id: '/fr/prompt/$slug',
  path: '/fr/prompt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FrBundleSlugRoute = FrBundleSlugRouteImport.update({
  id: '/fr/bundle/$slug',
  path: '/fr/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EsPromptSlugRoute = EsPromptSlugRouteImport.update({
  id: '/es/prompt/$slug',
  path: '/es/prompt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EsBundleSlugRoute = EsBundleSlugRouteImport.update({
  id: '/es/bundle/$slug',
  path: '/es/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DePromptSlugRoute = DePromptSlugRouteImport.update({
  id: '/de/prompt/$slug',
  path: '/de/prompt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DeBundleSlugRoute = DeBundleSlugRouteImport.update({
  id: '/de/bundle/$slug',
  path: '/de/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/ats': typeof AtsRoute
  '/bundles': typeof BundlesRoute
  '/cover-letter': typeof CoverLetterRoute
  '/creator': typeof CreatorRoute
  '/creators': typeof CreatorsRoute
  '/cv': typeof CvRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/import': typeof AdminImportRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/de/ats': typeof DeAtsRoute
  '/de/bundles': typeof DeBundlesRoute
  '/de/cover-letter': typeof DeCoverLetterRoute
  '/de/creator': typeof DeCreatorRoute
  '/de/creators': typeof DeCreatorsRoute
  '/de/cv': typeof DeCvRoute
  '/de/marketplace': typeof DeMarketplaceRoute
  '/de/pricing': typeof DePricingRoute
  '/es/ats': typeof EsAtsRoute
  '/es/bundles': typeof EsBundlesRoute
  '/es/cover-letter': typeof EsCoverLetterRoute
  '/es/creator': typeof EsCreatorRoute
  '/es/creators': typeof EsCreatorsRoute
  '/es/cv': typeof EsCvRoute
  '/es/marketplace': typeof EsMarketplaceRoute
  '/es/pricing': typeof EsPricingRoute
  '/fr/ats': typeof FrAtsRoute
  '/fr/bundles': typeof FrBundlesRoute
  '/fr/cover-letter': typeof FrCoverLetterRoute
  '/fr/creator': typeof FrCreatorRoute
  '/fr/creators': typeof FrCreatorsRoute
  '/fr/cv': typeof FrCvRoute
  '/fr/marketplace': typeof FrMarketplaceRoute
  '/fr/pricing': typeof FrPricingRoute
  '/it/ats': typeof ItAtsRoute
  '/it/bundles': typeof ItBundlesRoute
  '/it/cover-letter': typeof ItCoverLetterRoute
  '/it/creator': typeof ItCreatorRoute
  '/it/creators': typeof ItCreatorsRoute
  '/it/cv': typeof ItCvRoute
  '/it/marketplace': typeof ItMarketplaceRoute
  '/it/pricing': typeof ItPricingRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/de/': typeof DeIndexRoute
  '/es/': typeof EsIndexRoute
  '/fr/': typeof FrIndexRoute
  '/ger/': typeof GerIndexRoute
  '/it/': typeof ItIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/de/bundle/$slug': typeof DeBundleSlugRoute
  '/de/prompt/$slug': typeof DePromptSlugRoute
  '/es/bundle/$slug': typeof EsBundleSlugRoute
  '/es/prompt/$slug': typeof EsPromptSlugRoute
  '/fr/bundle/$slug': typeof FrBundleSlugRoute
  '/fr/prompt/$slug': typeof FrPromptSlugRoute
  '/it/bundle/$slug': typeof ItBundleSlugRoute
  '/it/prompt/$slug': typeof ItPromptSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/ats': typeof AtsRoute
  '/bundles': typeof BundlesRoute
  '/cover-letter': typeof CoverLetterRoute
  '/creator': typeof CreatorRoute
  '/creators': typeof CreatorsRoute
  '/cv': typeof CvRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/import': typeof AdminImportRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/de/ats': typeof DeAtsRoute
  '/de/bundles': typeof DeBundlesRoute
  '/de/cover-letter': typeof DeCoverLetterRoute
  '/de/creator': typeof DeCreatorRoute
  '/de/creators': typeof DeCreatorsRoute
  '/de/cv': typeof DeCvRoute
  '/de/marketplace': typeof DeMarketplaceRoute
  '/de/pricing': typeof DePricingRoute
  '/es/ats': typeof EsAtsRoute
  '/es/bundles': typeof EsBundlesRoute
  '/es/cover-letter': typeof EsCoverLetterRoute
  '/es/creator': typeof EsCreatorRoute
  '/es/creators': typeof EsCreatorsRoute
  '/es/cv': typeof EsCvRoute
  '/es/marketplace': typeof EsMarketplaceRoute
  '/es/pricing': typeof EsPricingRoute
  '/fr/ats': typeof FrAtsRoute
  '/fr/bundles': typeof FrBundlesRoute
  '/fr/cover-letter': typeof FrCoverLetterRoute
  '/fr/creator': typeof FrCreatorRoute
  '/fr/creators': typeof FrCreatorsRoute
  '/fr/cv': typeof FrCvRoute
  '/fr/marketplace': typeof FrMarketplaceRoute
  '/fr/pricing': typeof FrPricingRoute
  '/it/ats': typeof ItAtsRoute
  '/it/bundles': typeof ItBundlesRoute
  '/it/cover-letter': typeof ItCoverLetterRoute
  '/it/creator': typeof ItCreatorRoute
  '/it/creators': typeof ItCreatorsRoute
  '/it/cv': typeof ItCvRoute
  '/it/marketplace': typeof ItMarketplaceRoute
  '/it/pricing': typeof ItPricingRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/de': typeof DeIndexRoute
  '/es': typeof EsIndexRoute
  '/fr': typeof FrIndexRoute
  '/ger': typeof GerIndexRoute
  '/it': typeof ItIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/de/bundle/$slug': typeof DeBundleSlugRoute
  '/de/prompt/$slug': typeof DePromptSlugRoute
  '/es/bundle/$slug': typeof EsBundleSlugRoute
  '/es/prompt/$slug': typeof EsPromptSlugRoute
  '/fr/bundle/$slug': typeof FrBundleSlugRoute
  '/fr/prompt/$slug': typeof FrPromptSlugRoute
  '/it/bundle/$slug': typeof ItBundleSlugRoute
  '/it/prompt/$slug': typeof ItPromptSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/ats': typeof AtsRoute
  '/bundles': typeof BundlesRoute
  '/cover-letter': typeof CoverLetterRoute
  '/creator': typeof CreatorRoute
  '/creators': typeof CreatorsRoute
  '/cv': typeof CvRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/import': typeof AdminImportRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/de/ats': typeof DeAtsRoute
  '/de/bundles': typeof DeBundlesRoute
  '/de/cover-letter': typeof DeCoverLetterRoute
  '/de/creator': typeof DeCreatorRoute
  '/de/creators': typeof DeCreatorsRoute
  '/de/cv': typeof DeCvRoute
  '/de/marketplace': typeof DeMarketplaceRoute
  '/de/pricing': typeof DePricingRoute
  '/es/ats': typeof EsAtsRoute
  '/es/bundles': typeof EsBundlesRoute
  '/es/cover-letter': typeof EsCoverLetterRoute
  '/es/creator': typeof EsCreatorRoute
  '/es/creators': typeof EsCreatorsRoute
  '/es/cv': typeof EsCvRoute
  '/es/marketplace': typeof EsMarketplaceRoute
  '/es/pricing': typeof EsPricingRoute
  '/fr/ats': typeof FrAtsRoute
  '/fr/bundles': typeof FrBundlesRoute
  '/fr/cover-letter': typeof FrCoverLetterRoute
  '/fr/creator': typeof FrCreatorRoute
  '/fr/creators': typeof FrCreatorsRoute
  '/fr/cv': typeof FrCvRoute
  '/fr/marketplace': typeof FrMarketplaceRoute
  '/fr/pricing': typeof FrPricingRoute
  '/it/ats': typeof ItAtsRoute
  '/it/bundles': typeof ItBundlesRoute
  '/it/cover-letter': typeof ItCoverLetterRoute
  '/it/creator': typeof ItCreatorRoute
  '/it/creators': typeof ItCreatorsRoute
  '/it/cv': typeof ItCvRoute
  '/it/marketplace': typeof ItMarketplaceRoute
  '/it/pricing': typeof ItPricingRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/de/': typeof DeIndexRoute
  '/es/': typeof EsIndexRoute
  '/fr/': typeof FrIndexRoute
  '/ger/': typeof GerIndexRoute
  '/it/': typeof ItIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/de/bundle/$slug': typeof DeBundleSlugRoute
  '/de/prompt/$slug': typeof DePromptSlugRoute
  '/es/bundle/$slug': typeof EsBundleSlugRoute
  '/es/prompt/$slug': typeof EsPromptSlugRoute
  '/fr/bundle/$slug': typeof FrBundleSlugRoute
  '/fr/prompt/$slug': typeof FrPromptSlugRoute
  '/it/bundle/$slug': typeof ItBundleSlugRoute
  '/it/prompt/$slug': typeof ItPromptSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/ats'
    | '/bundles'
    | '/cover-letter'
    | '/creator'
    | '/creators'
    | '/cv'
    | '/dashboard'
    | '/library'
    | '/login'
    | '/marketplace'
    | '/mcp'
    | '/pricing'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/import'
    | '/bundle/$slug'
    | '/de/ats'
    | '/de/bundles'
    | '/de/cover-letter'
    | '/de/creator'
    | '/de/creators'
    | '/de/cv'
    | '/de/marketplace'
    | '/de/pricing'
    | '/es/ats'
    | '/es/bundles'
    | '/es/cover-letter'
    | '/es/creator'
    | '/es/creators'
    | '/es/cv'
    | '/es/marketplace'
    | '/es/pricing'
    | '/fr/ats'
    | '/fr/bundles'
    | '/fr/cover-letter'
    | '/fr/creator'
    | '/fr/creators'
    | '/fr/cv'
    | '/fr/marketplace'
    | '/fr/pricing'
    | '/it/ats'
    | '/it/bundles'
    | '/it/cover-letter'
    | '/it/creator'
    | '/it/creators'
    | '/it/cv'
    | '/it/marketplace'
    | '/it/pricing'
    | '/prompt/$slug'
    | '/de/'
    | '/es/'
    | '/fr/'
    | '/ger/'
    | '/it/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/de/bundle/$slug'
    | '/de/prompt/$slug'
    | '/es/bundle/$slug'
    | '/es/prompt/$slug'
    | '/fr/bundle/$slug'
    | '/fr/prompt/$slug'
    | '/it/bundle/$slug'
    | '/it/prompt/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/ats'
    | '/bundles'
    | '/cover-letter'
    | '/creator'
    | '/creators'
    | '/cv'
    | '/dashboard'
    | '/library'
    | '/login'
    | '/marketplace'
    | '/mcp'
    | '/pricing'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/import'
    | '/bundle/$slug'
    | '/de/ats'
    | '/de/bundles'
    | '/de/cover-letter'
    | '/de/creator'
    | '/de/creators'
    | '/de/cv'
    | '/de/marketplace'
    | '/de/pricing'
    | '/es/ats'
    | '/es/bundles'
    | '/es/cover-letter'
    | '/es/creator'
    | '/es/creators'
    | '/es/cv'
    | '/es/marketplace'
    | '/es/pricing'
    | '/fr/ats'
    | '/fr/bundles'
    | '/fr/cover-letter'
    | '/fr/creator'
    | '/fr/creators'
    | '/fr/cv'
    | '/fr/marketplace'
    | '/fr/pricing'
    | '/it/ats'
    | '/it/bundles'
    | '/it/cover-letter'
    | '/it/creator'
    | '/it/creators'
    | '/it/cv'
    | '/it/marketplace'
    | '/it/pricing'
    | '/prompt/$slug'
    | '/de'
    | '/es'
    | '/fr'
    | '/ger'
    | '/it'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/de/bundle/$slug'
    | '/de/prompt/$slug'
    | '/es/bundle/$slug'
    | '/es/prompt/$slug'
    | '/fr/bundle/$slug'
    | '/fr/prompt/$slug'
    | '/it/bundle/$slug'
    | '/it/prompt/$slug'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/ats'
    | '/bundles'
    | '/cover-letter'
    | '/creator'
    | '/creators'
    | '/cv'
    | '/dashboard'
    | '/library'
    | '/login'
    | '/marketplace'
    | '/mcp'
    | '/pricing'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/import'
    | '/bundle/$slug'
    | '/de/ats'
    | '/de/bundles'
    | '/de/cover-letter'
    | '/de/creator'
    | '/de/creators'
    | '/de/cv'
    | '/de/marketplace'
    | '/de/pricing'
    | '/es/ats'
    | '/es/bundles'
    | '/es/cover-letter'
    | '/es/creator'
    | '/es/creators'
    | '/es/cv'
    | '/es/marketplace'
    | '/es/pricing'
    | '/fr/ats'
    | '/fr/bundles'
    | '/fr/cover-letter'
    | '/fr/creator'
    | '/fr/creators'
    | '/fr/cv'
    | '/fr/marketplace'
    | '/fr/pricing'
    | '/it/ats'
    | '/it/bundles'
    | '/it/cover-letter'
    | '/it/creator'
    | '/it/creators'
    | '/it/cv'
    | '/it/marketplace'
    | '/it/pricing'
    | '/prompt/$slug'
    | '/de/'
    | '/es/'
    | '/fr/'
    | '/ger/'
    | '/it/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/de/bundle/$slug'
    | '/de/prompt/$slug'
    | '/es/bundle/$slug'
    | '/es/prompt/$slug'
    | '/fr/bundle/$slug'
    | '/fr/prompt/$slug'
    | '/it/bundle/$slug'
    | '/it/prompt/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AtsRoute: typeof AtsRoute
  BundlesRoute: typeof BundlesRoute
  CoverLetterRoute: typeof CoverLetterRoute
  CreatorRoute: typeof CreatorRoute
  CreatorsRoute: typeof CreatorsRoute
  CvRoute: typeof CvRoute
  DashboardRoute: typeof DashboardRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminImportRoute: typeof AdminImportRoute
  BundleSlugRoute: typeof BundleSlugRoute
  DeAtsRoute: typeof DeAtsRoute
  DeBundlesRoute: typeof DeBundlesRoute
  DeCoverLetterRoute: typeof DeCoverLetterRoute
  DeCreatorRoute: typeof DeCreatorRoute
  DeCreatorsRoute: typeof DeCreatorsRoute
  DeCvRoute: typeof DeCvRoute
  DeMarketplaceRoute: typeof DeMarketplaceRoute
  DePricingRoute: typeof DePricingRoute
  EsAtsRoute: typeof EsAtsRoute
  EsBundlesRoute: typeof EsBundlesRoute
  EsCoverLetterRoute: typeof EsCoverLetterRoute
  EsCreatorRoute: typeof EsCreatorRoute
  EsCreatorsRoute: typeof EsCreatorsRoute
  EsCvRoute: typeof EsCvRoute
  EsMarketplaceRoute: typeof EsMarketplaceRoute
  EsPricingRoute: typeof EsPricingRoute
  FrAtsRoute: typeof FrAtsRoute
  FrBundlesRoute: typeof FrBundlesRoute
  FrCoverLetterRoute: typeof FrCoverLetterRoute
  FrCreatorRoute: typeof FrCreatorRoute
  FrCreatorsRoute: typeof FrCreatorsRoute
  FrCvRoute: typeof FrCvRoute
  FrMarketplaceRoute: typeof FrMarketplaceRoute
  FrPricingRoute: typeof FrPricingRoute
  ItAtsRoute: typeof ItAtsRoute
  ItBundlesRoute: typeof ItBundlesRoute
  ItCoverLetterRoute: typeof ItCoverLetterRoute
  ItCreatorRoute: typeof ItCreatorRoute
  ItCreatorsRoute: typeof ItCreatorsRoute
  ItCvRoute: typeof ItCvRoute
  ItMarketplaceRoute: typeof ItMarketplaceRoute
  ItPricingRoute: typeof ItPricingRoute
  PromptSlugRoute: typeof PromptSlugRoute
  DeIndexRoute: typeof DeIndexRoute
  EsIndexRoute: typeof EsIndexRoute
  FrIndexRoute: typeof FrIndexRoute
  GerIndexRoute: typeof GerIndexRoute
  ItIndexRoute: typeof ItIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  DeBundleSlugRoute: typeof DeBundleSlugRoute
  DePromptSlugRoute: typeof DePromptSlugRoute
  EsBundleSlugRoute: typeof EsBundleSlugRoute
  EsPromptSlugRoute: typeof EsPromptSlugRoute
  FrBundleSlugRoute: typeof FrBundleSlugRoute
  FrPromptSlugRoute: typeof FrPromptSlugRoute
  ItBundleSlugRoute: typeof ItBundleSlugRoute
  ItPromptSlugRoute: typeof ItPromptSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter': {
      id: '/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof CoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats': {
      id: '/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof AtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/': {
      id: '/it/'
      path: '/it'
      fullPath: '/it/'
      preLoaderRoute: typeof ItIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ger/': {
      id: '/ger/'
      path: '/ger'
      fullPath: '/ger/'
      preLoaderRoute: typeof GerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/': {
      id: '/de/'
      path: '/de'
      fullPath: '/de/'
      preLoaderRoute: typeof DeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt/$slug': {
      id: '/prompt/$slug'
      path: '/prompt/$slug'
      fullPath: '/prompt/$slug'
      preLoaderRoute: typeof PromptSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/pricing': {
      id: '/it/pricing'
      path: '/it/pricing'
      fullPath: '/it/pricing'
      preLoaderRoute: typeof ItPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/marketplace': {
      id: '/it/marketplace'
      path: '/it/marketplace'
      fullPath: '/it/marketplace'
      preLoaderRoute: typeof ItMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/cv': {
      id: '/it/cv'
      path: '/it/cv'
      fullPath: '/it/cv'
      preLoaderRoute: typeof ItCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/creators': {
      id: '/it/creators'
      path: '/it/creators'
      fullPath: '/it/creators'
      preLoaderRoute: typeof ItCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/creator': {
      id: '/it/creator'
      path: '/it/creator'
      fullPath: '/it/creator'
      preLoaderRoute: typeof ItCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/cover-letter': {
      id: '/it/cover-letter'
      path: '/it/cover-letter'
      fullPath: '/it/cover-letter'
      preLoaderRoute: typeof ItCoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/bundles': {
      id: '/it/bundles'
      path: '/it/bundles'
      fullPath: '/it/bundles'
      preLoaderRoute: typeof ItBundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/ats': {
      id: '/it/ats'
      path: '/it/ats'
      fullPath: '/it/ats'
      preLoaderRoute: typeof ItAtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/pricing': {
      id: '/fr/pricing'
      path: '/fr/pricing'
      fullPath: '/fr/pricing'
      preLoaderRoute: typeof FrPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/marketplace': {
      id: '/fr/marketplace'
      path: '/fr/marketplace'
      fullPath: '/fr/marketplace'
      preLoaderRoute: typeof FrMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/cv': {
      id: '/fr/cv'
      path: '/fr/cv'
      fullPath: '/fr/cv'
      preLoaderRoute: typeof FrCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/creators': {
      id: '/fr/creators'
      path: '/fr/creators'
      fullPath: '/fr/creators'
      preLoaderRoute: typeof FrCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/creator': {
      id: '/fr/creator'
      path: '/fr/creator'
      fullPath: '/fr/creator'
      preLoaderRoute: typeof FrCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/cover-letter': {
      id: '/fr/cover-letter'
      path: '/fr/cover-letter'
      fullPath: '/fr/cover-letter'
      preLoaderRoute: typeof FrCoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/bundles': {
      id: '/fr/bundles'
      path: '/fr/bundles'
      fullPath: '/fr/bundles'
      preLoaderRoute: typeof FrBundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/ats': {
      id: '/fr/ats'
      path: '/fr/ats'
      fullPath: '/fr/ats'
      preLoaderRoute: typeof FrAtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/pricing': {
      id: '/es/pricing'
      path: '/es/pricing'
      fullPath: '/es/pricing'
      preLoaderRoute: typeof EsPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/marketplace': {
      id: '/es/marketplace'
      path: '/es/marketplace'
      fullPath: '/es/marketplace'
      preLoaderRoute: typeof EsMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/cv': {
      id: '/es/cv'
      path: '/es/cv'
      fullPath: '/es/cv'
      preLoaderRoute: typeof EsCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/creators': {
      id: '/es/creators'
      path: '/es/creators'
      fullPath: '/es/creators'
      preLoaderRoute: typeof EsCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/creator': {
      id: '/es/creator'
      path: '/es/creator'
      fullPath: '/es/creator'
      preLoaderRoute: typeof EsCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/cover-letter': {
      id: '/es/cover-letter'
      path: '/es/cover-letter'
      fullPath: '/es/cover-letter'
      preLoaderRoute: typeof EsCoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/bundles': {
      id: '/es/bundles'
      path: '/es/bundles'
      fullPath: '/es/bundles'
      preLoaderRoute: typeof EsBundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/ats': {
      id: '/es/ats'
      path: '/es/ats'
      fullPath: '/es/ats'
      preLoaderRoute: typeof EsAtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/pricing': {
      id: '/de/pricing'
      path: '/de/pricing'
      fullPath: '/de/pricing'
      preLoaderRoute: typeof DePricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/marketplace': {
      id: '/de/marketplace'
      path: '/de/marketplace'
      fullPath: '/de/marketplace'
      preLoaderRoute: typeof DeMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/cv': {
      id: '/de/cv'
      path: '/de/cv'
      fullPath: '/de/cv'
      preLoaderRoute: typeof DeCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/creators': {
      id: '/de/creators'
      path: '/de/creators'
      fullPath: '/de/creators'
      preLoaderRoute: typeof DeCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/creator': {
      id: '/de/creator'
      path: '/de/creator'
      fullPath: '/de/creator'
      preLoaderRoute: typeof DeCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/cover-letter': {
      id: '/de/cover-letter'
      path: '/de/cover-letter'
      fullPath: '/de/cover-letter'
      preLoaderRoute: typeof DeCoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/bundles': {
      id: '/de/bundles'
      path: '/de/bundles'
      fullPath: '/de/bundles'
      preLoaderRoute: typeof DeBundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/ats': {
      id: '/de/ats'
      path: '/de/ats'
      fullPath: '/de/ats'
      preLoaderRoute: typeof DeAtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle/$slug': {
      id: '/bundle/$slug'
      path: '/bundle/$slug'
      fullPath: '/bundle/$slug'
      preLoaderRoute: typeof BundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/prompt/$slug': {
      id: '/it/prompt/$slug'
      path: '/it/prompt/$slug'
      fullPath: '/it/prompt/$slug'
      preLoaderRoute: typeof ItPromptSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/bundle/$slug': {
      id: '/it/bundle/$slug'
      path: '/it/bundle/$slug'
      fullPath: '/it/bundle/$slug'
      preLoaderRoute: typeof ItBundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/prompt/$slug': {
      id: '/fr/prompt/$slug'
      path: '/fr/prompt/$slug'
      fullPath: '/fr/prompt/$slug'
      preLoaderRoute: typeof FrPromptSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/bundle/$slug': {
      id: '/fr/bundle/$slug'
      path: '/fr/bundle/$slug'
      fullPath: '/fr/bundle/$slug'
      preLoaderRoute: typeof FrBundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/prompt/$slug': {
      id: '/es/prompt/$slug'
      path: '/es/prompt/$slug'
      fullPath: '/es/prompt/$slug'
      preLoaderRoute: typeof EsPromptSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/bundle/$slug': {
      id: '/es/bundle/$slug'
      path: '/es/bundle/$slug'
      fullPath: '/es/bundle/$slug'
      preLoaderRoute: typeof EsBundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/prompt/$slug': {
      id: '/de/prompt/$slug'
      path: '/de/prompt/$slug'
      fullPath: '/de/prompt/$slug'
      preLoaderRoute: typeof DePromptSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/bundle/$slug': {
      id: '/de/bundle/$slug'
      path: '/de/bundle/$slug'
      fullPath: '/de/bundle/$slug'
      preLoaderRoute: typeof DeBundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AtsRoute: AtsRoute,
  BundlesRoute: BundlesRoute,
  CoverLetterRoute: CoverLetterRoute,
  CreatorRoute: CreatorRoute,
  CreatorsRoute: CreatorsRoute,
  CvRoute: CvRoute,
  DashboardRoute: DashboardRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminImportRoute: AdminImportRoute,
  BundleSlugRoute: BundleSlugRoute,
  DeAtsRoute: DeAtsRoute,
  DeBundlesRoute: DeBundlesRoute,
  DeCoverLetterRoute: DeCoverLetterRoute,
  DeCreatorRoute: DeCreatorRoute,
  DeCreatorsRoute: DeCreatorsRoute,
  DeCvRoute: DeCvRoute,
  DeMarketplaceRoute: DeMarketplaceRoute,
  DePricingRoute: DePricingRoute,
  EsAtsRoute: EsAtsRoute,
  EsBundlesRoute: EsBundlesRoute,
  EsCoverLetterRoute: EsCoverLetterRoute,
  EsCreatorRoute: EsCreatorRoute,
  EsCreatorsRoute: EsCreatorsRoute,
  EsCvRoute: EsCvRoute,
  EsMarketplaceRoute: EsMarketplaceRoute,
  EsPricingRoute: EsPricingRoute,
  FrAtsRoute: FrAtsRoute,
  FrBundlesRoute: FrBundlesRoute,
  FrCoverLetterRoute: FrCoverLetterRoute,
  FrCreatorRoute: FrCreatorRoute,
  FrCreatorsRoute: FrCreatorsRoute,
  FrCvRoute: FrCvRoute,
  FrMarketplaceRoute: FrMarketplaceRoute,
  FrPricingRoute: FrPricingRoute,
  ItAtsRoute: ItAtsRoute,
  ItBundlesRoute: ItBundlesRoute,
  ItCoverLetterRoute: ItCoverLetterRoute,
  ItCreatorRoute: ItCreatorRoute,
  ItCreatorsRoute: ItCreatorsRoute,
  ItCvRoute: ItCvRoute,
  ItMarketplaceRoute: ItMarketplaceRoute,
  ItPricingRoute: ItPricingRoute,
  PromptSlugRoute: PromptSlugRoute,
  DeIndexRoute: DeIndexRoute,
  EsIndexRoute: EsIndexRoute,
  FrIndexRoute: FrIndexRoute,
  GerIndexRoute: GerIndexRoute,
  ItIndexRoute: ItIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  DeBundleSlugRoute: DeBundleSlugRoute,
  DePromptSlugRoute: DePromptSlugRoute,
  EsBundleSlugRoute: EsBundleSlugRoute,
  EsPromptSlugRoute: EsPromptSlugRoute,
  FrBundleSlugRoute: FrBundleSlugRoute,
  FrPromptSlugRoute: FrPromptSlugRoute,
  ItBundleSlugRoute: ItBundleSlugRoute,
  ItPromptSlugRoute: ItPromptSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
